local _, addonTable = ...

if not addonTable then
    return
end

addonTable.WotLKGlyphs = {
    WARRIOR = {
        major = {
            "Glyph of Intervene",
            "Glyph of Last Stand",
            "Glyph of Vigilance",
            "Glyph of Enraged Regeneration",
            "Glyph of Shield Wall",
            "Glyph of Victory Rush",
            "Glyph of Resonating Power",
            "Glyph of Shockwave",
            "Glyph of Bloodthirst",
            "Glyph of Bladestorm",
            "Glyph of Devastate",
            "Glyph of Taunt",
            "Glyph of Blocking",
            "Glyph of Mortal Strike",
            "Glyph of Spell Reflection",
            "Glyph of Whirlwind",
            "Glyph of Sweeping Strikes",
            "Glyph of Execution",
            "Glyph of Cleaving",
            "Glyph of Barbaric Insults",
            "Glyph of Revenge",
            "Glyph of Overpower",
            "Glyph of Sunder Armor",
            "Glyph of Hamstring",
            "Glyph of Rending",
            "Glyph of Heroic Strike",
            "Glyph of Rapid Charge",
        },
        minor = {
            "Glyph of Enduring Victory",
            "Glyph of Mocking Blow",
            "Glyph of Charge",
            "Glyph of Bloodrage",
            "Glyph of Thunder Clap",
            "Glyph of Command",
            "Glyph of Battle",
        },
    },
    PALADIN = {
        major = {
            "Glyph of Shield of Righteousness",
            "Glyph of Avenging Wrath",
            "Glyph of Divine Storm",
            "Glyph of Seal of Light",
            "Glyph of Hammer of Wrath",
            "Glyph of Salvation",
            "Glyph of Avenger's Shield",
            "Glyph of Holy Shock",
            "Glyph of Turn Evil",
            "Glyph of Seal of Righteousness",
            "Glyph of Divine Plea",
            "Glyph of Holy Wrath",
            "Glyph of Seal of Vengeance",
            "Glyph of Seal of Wisdom",
            "Glyph of Beacon of Light",
            "Glyph of Hammer of the Righteous",
            "Glyph of Seal of Command",
            "Glyph of Flash of Light",
            "Glyph of Exorcism",
            "Glyph of Crusader Strike",
            "Glyph of Consecration",
            "Glyph of Cleansing",
            "Glyph of Divinity",
            "Glyph of Judgement",
            "Glyph of Hammer of Justice",
            "Glyph of Spiritual Attunement",
            "Glyph of Righteous Defense",
        },
        minor = {
            "Glyph of Lay on Hands",
            "Glyph of the Wise",
            "Glyph of Blessing of Kings",
            "Glyph of Blessing of Might",
            "Glyph of Sense Undead",
            "Glyph of Blessing of Wisdom",
        },
    },
    HUNTER = {
        major = {
            "Glyph of Scatter Shot",
            "Glyph of Chimera Shot",
            "Glyph of Volley",
            "Glyph of Raptor Strike",
            "Glyph of Aspect of the Hawk",
            "Glyph of Aspect of the Viper",
            "Glyph of Explosive Trap",
            "Glyph of Wyvern Sting",
            "Glyph of Trueshot Aura",
            "Glyph of Kill Shot",
            "Glyph of Explosive Shot",
            "Glyph of Snake Trap",
            "Glyph of Steady Shot",
            "Glyph of Bestial Wrath",
            "Glyph of Aspect of the Beast",
            "Glyph of Frost Trap",
            "Glyph of Rapid Fire",
            "Glyph of Freezing Trap",
            "Glyph of Disengage",
            "Glyph of Deterrence",
            "Glyph of Aimed Shot",
            "Glyph of Multi-Shot",
            "Glyph of Immolation Trap",
            "Glyph of Mending",
            "Glyph of Arcane Shot",
            "Glyph of Serpent Sting",
            "Glyph of Hunter's Mark",
        },
        minor = {
            "Glyph of Feign Death",
            "Glyph of Mend Pet",
            "Glyph of Possessed Strength",
            "Glyph of Revive Pet",
            "Glyph of the Pack",
            "Glyph of Scare Beast",
        },
    },
    ROGUE = {
        major = {
            "Glyph of Deadly Throw",
            "Glyph of Crippling Poison",
            "Glyph of Preparation",
            "Glyph of Blade Flurry",
            "Glyph of Cloak of Shadows",
            "Glyph of Fan of Knives",
            "Glyph of Rupture",
            "Glyph of Ghostly Strike",
            "Glyph of Tricks of the Trade",
            "Glyph of Hemorrhage",
            "Glyph of Shadow Dance",
            "Glyph of Killing Spree",
            "Glyph of Vigor",
            "Glyph of Hunger for Blood",
            "Glyph of Ambush",
            "Glyph of Feint",
            "Glyph of Sprint",
            "Glyph of Mutilate",
            "Glyph of Slice and Dice",
            "Glyph of Sinister Strike",
            "Glyph of Sap",
            "Glyph of Gouge",
            "Glyph of Garrote",
            "Glyph of Expose Armor",
            "Glyph of Eviscerate",
            "Glyph of Evasion",
            "Glyph of Backstab",
        },
        minor = {
            "Glyph of Blurred Speed",
            "Glyph of Vanish",
            "Glyph of Pick Lock",
            "Glyph of Distract",
            "Glyph of Safe Fall",
            "Glyph of Pick Pocket",
        },
    },
    PRIEST = {
        major = {
            "Glyph of Lightwell",
            "Glyph of Shadow Word: Death",
            "Glyph of Mass Dispel",
            "Glyph of Prayer of Healing",
            "Glyph of Mind Control",
            "Glyph of Guardian Spirit",
            "Glyph of Mind Sear",
            "Glyph of Spirit of Redemption",
            "Glyph of Circle of Healing",
            "Glyph of Penance",
            "Glyph of Dispersion",
            "Glyph of Scourge Imprisonment",
            "Glyph of Hymn of Hope",
            "Glyph of Shadow",
            "Glyph of Shadow Word: Pain",
            "Glyph of Holy Nova",
            "Glyph of Fear Ward",
            "Glyph of Pain Suppression",
            "Glyph of Dispel Magic",
            "Glyph of Smite",
            "Glyph of Mind Flay",
            "Glyph of Renew",
            "Glyph of Inner Fire",
            "Glyph of Flash Heal",
            "Glyph of Fade",
            "Glyph of Psychic Scream",
            "Glyph of Power Word: Shield",
        },
        minor = {
            "Glyph of Levitate",
            "Glyph of Shadowfiend",
            "Glyph of Fading",
            "Glyph of Shadow Protection",
            "Glyph of Fortitude",
            "Glyph of Shackle Undead",
        },
    },
    DEATHKNIGHT = {
        major = {
            "Glyph of Strangulate",
            "Glyph of Rune Strike",
            "Glyph of Heart Strike",
            "Glyph of Anti-Magic Shell",
            "Glyph of Icebound Fortitude",
            "Glyph of Dancing Rune Weapon",
            "Glyph of Chains of Ice",
            "Glyph of Unholy Blight",
            "Glyph of Hungering Cold",
            "Glyph of Howling Blast",
            "Glyph of Dark Command",
            "Glyph of Obliterate",
            "Glyph of Death and Decay",
            "Glyph of the Ghoul",
            "Glyph of Vampiric Blood",
            "Glyph of Death Strike",
            "Glyph of Scourge Strike",
            "Glyph of Blood Strike",
            "Glyph of Rune Tap",
            "Glyph of Unbreakable Armor",
            "Glyph of Plague Strike",
            "Glyph of Death Grip",
            "Glyph of Icy Touch",
            "Glyph of Disease",
            "Glyph of Dark Death",
            "Glyph of Frost Strike",
            "Glyph of Bone Shield",
        },
        minor = {
            "Glyph of Raise Dead",
            "Glyph of Horn of Winter",
            "Glyph of Death's Embrace",
            "Glyph of Blood Tap",
            "Glyph of Pestilence",
            "Glyph of Corpse Explosion",
        },
    },
    SHAMAN = {
        major = {
            "Glyph of Hex",
            "Glyph of Stoneclaw Totem",
            "Glyph of Fire Elemental Totem",
            "Glyph of Feral Spirit",
            "Glyph of Thunder",
            "Glyph of Shocking",
            "Glyph of Chain Lightning",
            "Glyph of Healing Wave",
            "Glyph of Mana Tide Totem",
            "Glyph of Chain Heal",
            "Glyph of Riptide",
            "Glyph of Lava",
            "Glyph of Elemental Mastery",
            "Glyph of Stormstrike",
            "Glyph of Windfury Weapon",
            "Glyph of Earthliving Weapon",
            "Glyph of Water Mastery",
            "Glyph of Totem of Wrath",
            "Glyph of Earth Shield",
            "Glyph of Lesser Healing Wave",
            "Glyph of Healing Stream Totem",
            "Glyph of Frost Shock",
            "Glyph of Lava Lash",
            "Glyph of Lightning Bolt",
            "Glyph of Flametongue Weapon",
            "Glyph of Fire Nova",
            "Glyph of Lightning Shield",
            "Glyph of Flame Shock",
        },
        minor = {
            "Glyph of Ghost Wolf",
            "Glyph of Water Breathing",
            "Glyph of Renewed Life",
            "Glyph of Thunderstorm",
            "Glyph of Water Shield",
            "Glyph of Water Walking",
            "Glyph of Astral Recall",
        },
    },
    MAGE = {
        major = {
            "Glyph of Mirror Image",
            "Glyph of Ice Barrier",
            "Glyph of Polymorph",
            "Glyph of Deep Freeze",
            "Glyph of Invisibility",
            "Glyph of Ice Lance",
            "Glyph of Fire Blast",
            "Glyph of Fireball",
            "Glyph of Frostfire",
            "Glyph of Molten Armor",
            "Glyph of Remove Curse",
            "Glyph of Living Bomb",
            "Glyph of Water Elemental",
            "Glyph of Arcane Barrage",
            "Glyph of Arcane Power",
            "Glyph of Mage Armor",
            "Glyph of Arcane Blast",
            "Glyph of Mana Gem",
            "Glyph of Eternal Water",
            "Glyph of Ice Block",
            "Glyph of Scorch",
            "Glyph of Icy Veins",
            "Glyph of Evocation",
            "Glyph of Blink",
            "Glyph of Arcane Missiles",
            "Glyph of Arcane Explosion",
            "Glyph of Ice Armor",
            "Glyph of Frost Nova",
        },
        minor = {
            "Glyph of Frost Armor",
            "Glyph of Arcane Intellect",
            "Glyph of Frost Ward",
            "Glyph of the Penguin",
            "Glyph of Slow Fall",
            "Glyph of Blast Wave",
            "Glyph of Fire Ward",
        },
    },
    WARLOCK = {
        major = {
            "Glyph of Life Tap",
            "Glyph of Shadowflame",
            "Glyph of Unstable Affliction",
            "Glyph of Chaos Bolt",
            "Glyph of Death Coil",
            "Glyph of Curse of Agony",
            "Glyph of Felhunter",
            "Glyph of Soul Link",
            "Glyph of Howl of Terror",
            "Glyph of Immolate",
            "Glyph of Metamorphosis",
            "Glyph of Demonic Circle",
            "Glyph of Quick Decay",
            "Glyph of Felguard",
            "Glyph of Siphon Life",
            "Glyph of Conflagrate",
            "Glyph of Haunt",
            "Glyph of Incinerate",
            "Glyph of Succubus",
            "Glyph of Shadowburn",
            "Glyph of Soulstone",
            "Glyph of Searing Pain",
            "Glyph of Voidwalker",
            "Glyph of Shadow Bolt",
            "Glyph of Imp",
            "Glyph of Fear",
            "Glyph of Health Funnel",
            "Glyph of Healthstone",
            "Glyph of Corruption",
        },
        minor = {
            "Glyph of Souls",
            "Glyph of Drain Soul",
            "Glyph of Subjugate Demon",
            "Glyph of Unending Breath",
            "Glyph of Kilrogg",
        },
    },
    DRUID = {
        major = {
            "Glyph of Nourish",
            "Glyph of Berserk",
            "Glyph of Savage Roar",
            "Glyph of Mangle",
            "Glyph of Rapid Rejuvenation",
            "Glyph of Survival Instincts",
            "Glyph of Regrowth",
            "Glyph of Growl",
            "Glyph of Lifebloom",
            "Glyph of Barkskin",
            "Glyph of Focus",
            "Glyph of Innervate",
            "Glyph of Swiftmend",
            "Glyph of Wild Growth",
            "Glyph of Starfall",
            "Glyph of Frenzied Regeneration",
            "Glyph of Rake",
            "Glyph of Shred",
            "Glyph of Monsoon",
            "Glyph of Starfire",
            "Glyph of Rip",
            "Glyph of Rebirth",
            "Glyph of Insect Swarm",
            "Glyph of Moonfire",
            "Glyph of Healing Touch",
            "Glyph of Entangling Roots",
            "Glyph of Claw",
            "Glyph of Maul",
            "Glyph of Wrath",
            "Glyph of Rejuvenation",
        },
        minor = {
            "Glyph of Unburdened Rebirth",
            "Glyph of Thorns",
            "Glyph of Typhoon",
            "Glyph of Challenging Roar",
            "Glyph of the Wild",
            "Glyph of Dash",
            "Glyph of Aquatic Form",
        },
    },
}
